CREATE TABLE `questwireactions` (
  `QuestId` int(32) NOT NULL,
  `Ordinal` int(32) NOT NULL DEFAULT 0,
  `Version` int(32) NOT NULL,
  `ActionType` int(32) NOT NULL DEFAULT 0,
  `ActionInstance` int(32) NOT NULL DEFAULT 0,
  `Unknown1Type` int(32) NOT NULL DEFAULT 0,
  `Unknown1Instance` int(32) NOT NULL DEFAULT 0,
  `Unknown2Type` int(32) NOT NULL DEFAULT 0,
  `Unknown2Instance` int(32) NOT NULL DEFAULT 0,
  `Unknown3Type` int(32) NOT NULL DEFAULT 0,
  `Unknown3Instance` int(32) NOT NULL DEFAULT 0,
  `Unknown4Type` int(32) NOT NULL DEFAULT 0,
  `Unknown4Instance` int(32) NOT NULL DEFAULT 0,
  `Unknown5` float NOT NULL DEFAULT 0,
  `Unknown6` float NOT NULL DEFAULT 0,
  `Unknown7` float NOT NULL DEFAULT 0,
  `Unknown8` float NOT NULL DEFAULT 0,
  `Unknown9Type` int(32) NOT NULL DEFAULT 0,
  `Unknown9Instance` int(32) NOT NULL DEFAULT 0,
  `Unknown10` float NOT NULL DEFAULT 0,
  `Unknown11` float NOT NULL DEFAULT 0,
  `Unknown12` float NOT NULL DEFAULT 0,
  `Unknown13` float NOT NULL DEFAULT 0,
  `Unknown14Type` int(32) NOT NULL DEFAULT 0,
  `Unknown14Instance` int(32) NOT NULL DEFAULT 0,
  `Deadline` int(32) NOT NULL DEFAULT 0,
  `Unknown16` int(32) NOT NULL DEFAULT 0,
  `TrackingType` int(32) NOT NULL,
  `PlayfieldType` int(32) NOT NULL DEFAULT 40016,
  `PlayfieldInstance` int(32) NOT NULL DEFAULT 0,
  `Unknown18` int(32) NOT NULL DEFAULT 100000,
  `Unknown19` int(32) NOT NULL DEFAULT 100000,
  `X` float NOT NULL DEFAULT 0,
  `Y` float NOT NULL DEFAULT 0,
  `Z` float NOT NULL DEFAULT 0,
  PRIMARY KEY (`QuestId`,`Ordinal`) USING BTREE,
  CONSTRAINT `questwireactions_quest` FOREIGN KEY (`QuestId`) REFERENCES `quests` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
